import Navbar from './Navbar';
import Footer from './Footer';
import React from 'react'
import Head from 'next/head';
import dynamic from 'next/dynamic';
import styles from '@/styles/Home.module.css'


function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Flight booking website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>

                <div className={styles.gradient}>
                    <Navbar />

                    <main>
                        {children}
                    </main>
                </div>

                
                <Footer />


            </>
        </>
    )
}

export default dynamic(() => Promise.resolve(Layout), { ssr: false })
